title : Oh, Golden Years!
author :
  name : Sharon E. Rhodes
  email : rhodessharone@gmail.com
  github : serhodes
  twitter : sharonerhodes

navigation :
  - archive.html
  - tags.html
  - categories.html
